// Mocks generated by Mockito 5.0.16 from annotations
// in agora_fpa_service/test/fpa_service_test.dart.
// Do not manually edit this file.

import 'package:agora_fpa_service/src/fpa_config.dart' as _i3;
import 'package:agora_fpa_service/src/fpa_service.dart' as _i4;
import 'package:agora_fpa_service/src/native_fpa_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NativeFpaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNativeFpaService extends _i1.Mock implements _i2.NativeFpaService {
  @override
  int init(_i3.FpaConfig? config) =>
      (super.noSuchMethod(Invocation.method(#init, [config]), returnValue: 0)
          as int);
  @override
  void destroy() => super.noSuchMethod(Invocation.method(#destroy, []),
      returnValueForMissingStub: null);
  @override
  int getHttpProxyPort() =>
      (super.noSuchMethod(Invocation.method(#getHttpProxyPort, []),
          returnValue: 0) as int);
  @override
  int renewToken(String? token) => (super
          .noSuchMethod(Invocation.method(#renewToken, [token]), returnValue: 0)
      as int);
  @override
  int registerObserver(_i4.FpaServiceObserver? observer) =>
      (super.noSuchMethod(Invocation.method(#registerObserver, [observer]),
          returnValue: 0) as int);
  @override
  int unregisterObserver() =>
      (super.noSuchMethod(Invocation.method(#unregisterObserver, []),
          returnValue: 0) as int);
  @override
  int getServerStatus() => (super
          .noSuchMethod(Invocation.method(#getServerStatus, []), returnValue: 0)
      as int);
  @override
  int setParameters(String? params) =>
      (super.noSuchMethod(Invocation.method(#setParameters, [params]),
          returnValue: 0) as int);
  @override
  int updateChainIdTable(String? chainIdTableString) => (super.noSuchMethod(
      Invocation.method(#updateChainIdTable, [chainIdTableString]),
      returnValue: 0) as int);
  @override
  String toString() => super.toString();
}
